// The spine. Every write in the app goes through here. Nothing else writes.
// The scaffold's queued-ops shape is exactly what the real sync will POST.

import type { Operation, OperationStatus, OperationType, QueueSnapshot } from '../types';

type Listener = (snap: QueueSnapshot) => void;

interface QueueState {
  ops: Operation[];
  online: boolean;
  drainTimer: ReturnType<typeof setTimeout> | null;
  listeners: Set<Listener>;
}

const state: QueueState = {
  ops: [],
  online: true,
  drainTimer: null,
  listeners: new Set(),
};

const DRAIN_DELAY_MS = 1200; // one place, easy to delete

function snapshot(): QueueSnapshot {
  return { pending: state.ops.filter((o) => o.status === 'pending'), online: state.online };
}

function notify(): void {
  const snap = snapshot();
  state.listeners.forEach((fn) => fn(snap));
}

function scheduleDrain(): void {
  if (state.drainTimer !== null) return;
  state.drainTimer = setTimeout(() => {
    state.drainTimer = null;
    if (!state.online) return;
    const pending = state.ops.filter((o) => o.status === 'pending');
    if (pending.length === 0) return;
    state.ops = state.ops.map((o) =>
      o.status === 'pending' ? { ...o, status: 'synced' satisfies OperationStatus } : o,
    );
    notify();
  }, DRAIN_DELAY_MS);
}

/** Append an operation. The id must have been generated by the caller with crypto.randomUUID(). */
export function enqueue<P>(op: {
  type: OperationType;
  payload: P;
  createdAt: string;
  id?: string;
}): Operation<P> {
  const id = op.id ?? crypto.randomUUID();
  const entry: Operation<P> = {
    id,
    type: op.type,
    payload: op.payload,
    createdAt: op.createdAt,
    status: 'pending',
  };
  state.ops = [...state.ops, entry as Operation];
  notify();
  scheduleDrain();
  return entry;
}

/** Subscribe to queue changes. Returns an unsubscribe function. */
export function subscribe(fn: Listener): () => void {
  state.listeners.add(fn);
  fn(snapshot());
  return () => {
    state.listeners.delete(fn);
  };
}

/** Currently pending operations (not yet drained). */
export function pending(): Operation[] {
  return state.ops.filter((o) => o.status === 'pending');
}

/** All operations, latest first. Used by the sync sheet. */
export function history(): Operation[] {
  return [...state.ops].reverse();
}

/** Toggle the mock connection state — drives OFFLINE indicator. */
export function setOnline(online: boolean): void {
  state.online = online;
  notify();
  if (online) scheduleDrain();
}

export function isOnline(): boolean {
  return state.online;
}
